### ISSUE TITLE
About the weight initialization

### ISSUE THREAD

**Issue by rederyang** [bbbbbbzhou/DuDoRNet#7]
Hi! Thanks for your great work.

I am currently also working on deep learning-based MRI reconstruction and I am using DuDoRNet as the reconstruction network. I noticed that in the codebase, the network uses a special weight initialization, rather than the default initialization of pytorch. I am wondering why? Cause I found that if I used the default initialization, the convergence of the network became faster.

**Comment by bbbbbbzhou** [comment]
We initialed our weights with a Gaussian distribution. However, we agree other weight initialization strategies could help faster convergence in different datasets. We will leave this as an open question to explore for different users.
